/* 계좌/카드 데이터 조합(interface) */
export function convertTransAsset(asset) {
  const isCanceled = ["취소", "거절"].includes(asset.cardApprovalType);
  const cardData = {
    cardLog: asset._id,
    user: asset.user,
    userId: asset.userId,
    corpNum: asset.corpNum,
    corpName: asset.corpName,
    card: asset.card,
    cardCompany: asset.cardCompany,
    cardNum: asset.cardNum,
    cardType: asset.cardType,
    tradeKind: asset.tradeKind,
    tradeType: "C",
    useKind: asset.useKind,
    useDT: asset.useDT,
    transDate: asset.transDate,
    transMoney: parseInt(asset.cardApprovalCost),
    transAssetNum: asset.transAssetNum,
    cardApprovalType: asset.cardApprovalType,
    cardApprovalNum: asset.cardApprovalNum,
    cardApprovalCost: asset.cardApprovalCost,
    amount: asset.amount,
    tax: asset.tax,
    serviceCharge: asset.serviceCharge,
    totalAmount: asset.totalAmount,
    useStoreNum: asset.useStoreNum,
    useStoreCorpNum: asset.useStoreCorpNum,
    useStoreName: asset.useStoreName,
    useStoreAddr: asset.useStoreAddr,
    useStoreBizType: asset.useStoreBizType,
    useStoreTel: asset.useStoreTel,
    useStoreTaxType: asset.useStoreTaxType,
    paymentPlan: asset.paymentPlan,
    installmentMonths: asset.installmentMonths,
    currency: asset.currency,
    keyword: asset.keyword,
    useYn: !isCanceled,
  };

  const accountData = {
    accountLog: asset._id,
    user: asset.user,
    userId: asset.userId,
    useKind: asset.useKind,
    bank: asset.bank,
    corpNum: asset.corpNum,
    corpName: asset.corpName,
    bankAccountNum: asset.bankAccountNum,
    account: asset.account,
    withdraw: asset.withdraw,
    deposit: asset.deposit,
    balance: asset.balance,
    transDT: asset.transDT,
    transDate: asset.transDate,
    transMoney: parseInt(asset.deposit) || parseInt(asset.withdraw),
    tradeType: parseInt(asset.deposit) > 0 ? "D" : "C",
    transAssetNum: asset.transAssetNum,
    transType: asset.transType,
    transOffice: asset.transOffice,
    transRemark: asset.transRemark,
    transRefKey: asset.transRefKey,
    mgtRemark1: asset.mgtRemark1,
    mgtRemark2: asset.mgtRemark2,
    keyword: asset.keyword,
    useYn: !isCanceled,
  };

  return asset.cardNum ? cardData : accountData;
}
