@baseUrl = http://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxZDhiNGEyY2RhODg4MWU5NzkzNTYiLCJpYXQiOjE3MDIxMjgyODksImV4cCI6MTcwMjMwMTA4OX0.R5WxoB6OF-bnrxmE7GxUkBwymbRmgMeCRIx9z5sPzkI

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "userId": "bethelean", 
    "password": "12345678"
}

### 사용 않는 직원정보 자동 삭제
POST {{baseUrl}}/emp/auto-delete HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{

}
