@baseUrl = http://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxZDhiNGEyY2RhODg4MWU5NzkzNTYiLCJpYXQiOjE2OTcxNTkxOTAsImV4cCI6MTY5OTc1MTE5MH0.bwM8bXg885QzDnuTLPJlia92T9b2oCaj7h_9O437PO0

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "userId": "bethelean", 
    "password": "12345678"
}

### 거래분류
POST {{baseUrl}}/fin-status/amount HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "userId": "bethelean",
    "fromAt": "20230801",
    "toAt": "20230930"
}

### 세금계산서 합계 조회
POST {{baseUrl}}/fin-status/tax HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "userId": "bethelean",
    "fromAt": "20230901",
    "toAt": "20230930"
}

### 자산 합계 조회
POST {{baseUrl}}/fin-status/asset HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "userId": "bethelean",
    "fromAt": "20230901",
    "toAt": "20230930"
}