@baseUrl = http://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxZDhiNGEyY2RhODg4MWU5NzkzNTYiLCJpYXQiOjE2OTgwNDA0NDEsImV4cCI6MTcwMDYzMjQ0MX0.MwAlQLXCIxxMwMDgfcNXdLtGTtgNG9retpaeGS61ork

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "userId": "bethelean", 
    "password": "12345678"
}

### 세금계산서 사용 등록
POST {{baseUrl}}/tax/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
    "hometaxID": "bethelean",
    "hometaxPWD": "hj@28480404"
}

### 세금계산서 사용 재등록
POST {{baseUrl}}/tax/re-reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350"
}


### 세금계산서 발행 로그 저장
POST {{baseUrl}}/tax/reg-log HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "fromAt": "20230501",
    "toAt": "20231031"
}

### 세금계산서 발행 업체명 및 대표 이름 확인 
POST {{baseUrl}}/tax/isTax HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "userId": "bethelean",
    "fromAt": "20230801",
    "toAt": "20230930"
}
