@baseUrl = http://localhost:8089
#@baseUrl = http://mystoredata.bethelean.kr:8089

### 통장 로그 동기화
GET {{baseUrl}}/batch/sync-account HTTP/1.1
Content-Type: application/json; charset=UTF-8

### 카드 로그 동기화
GET {{baseUrl}}/batch/sync-card HTTP/1.1
Content-Type: application/json; charset=UTF-8

###  로그 동기화
GET {{baseUrl}}/batch/sync-merge HTTP/1.1
Content-Type: application/json; charset=UTF-8

###  취소 자동처리
GET {{baseUrl}}/trans/autoCancelCard?baseMonth=2023-05 HTTP/1.1
Content-Type: application/json; charset=UTF-

### sync test
GET {{baseUrl}}/batch/sync-test HTTP/1.1