@baseUrl = http://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxZDhiNGEyY2RhODg4MWU5NzkzNTYiLCJpYXQiOjE2OTk4NTQ0NTQsImV4cCI6MTcwMjQ0NjQ1NH0.WfbdG2V24BU3lo4IfaKqWvDZiLA0zrPv13kkTW2AzTA

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "userId": "bethelean", 
    "password": "12345678"
}


### 카드목록
GET {{baseUrl}}/card/list HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}


### 카드등록
POST {{baseUrl}}/card/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "cardCompany": "SHINHAN",
    "cardType": "P",
    "cardNum": "9410822093647032", 
    "webId": "iset12",
    "webPwd": "hj@28480404"
}

### 카드삭제
POST {{baseUrl}}/card/stop HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
	"cardNum": "9410822093647032"
}

### 카드내역불러와 저장
POST {{baseUrl}}/card/regLog HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "id": "iset12",
    "corpNum": "1073270598",
    "cardNum": "5594100017143644"
}

### 카드 재등록
POST {{baseUrl}}/card/re-reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
	"cardNum": "4336920003113475"
}

### 카드 재등록
POST {{baseUrl}}/card/cancel-stop HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
	"cardNum": "4336920003113475"
}
