@baseUrl = http://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxZDhiNGEyY2RhODg4MWU5NzkzNTYiLCJpYXQiOjE2OTUxODU2NDUsImV4cCI6MTY5Nzc3NzY0NX0.4nltAIBxj57jX2J2QnjqsWTkEr0MC9BWYCK70-BNHX8

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "userId": "bethelean", 
    "password": "12345678"
}

### 세금계산서 등록
POST {{baseUrl}}/tax/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
    "hometaxID": "bethelean",
    "hometaxPWD": "hj@28480404"
}


### 세금계산서 조회
POST {{baseUrl}}/tax/log HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
    "userId": "bethelean",
    "fromAt": "20230701",
    "toAt": "20230830"
}
