@baseUrl = https://localhost:8089

### 회원가입
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "login_id": "joon0227", 
    "password": "12345678",
    "name": "김희준",
    "email": "juni0227@nate.com",
    "corp_name": "아이셋코리아",
    "corp_ㅜㅕ": "아이셋코리아",
    "url": "bethelean.co.kr"
}

### 사용자 불러오기
GET {{baseUrl}}/user/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

### 카드목록
GET {{baseUrl}}/card/list?corpNum=1073270598 HTTP/1.1
Content-Type: application/json; charset=UTF-8

### 카드등록
POST {{baseUrl}}/card/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "cardCompany": "HANA",
    "cardType": "C",
    "cardNum": "4336920003113475",
    "webId": "BETHELEAN",
    "webPwd": "hj@28480404"
}

### 카드삭제
POST {{baseUrl}}/card/stop HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
	"cardNum": "4336920003113475"
}

### 카드내역불러오기
POST {{baseUrl}}/card/log HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "corpNum": "1073270598", 
    "id": "",
    "cardNum": "",
    "baseDate": ""
}


### 통장내역불러오기
GET {{baseUrl}}/account/log HTTP/1.1
Content-Type: application/json; charset=UTF-8


### 통장목록
GET {{baseUrl}}/account/list HTTP/1.1
Content-Type: application/json; charset=UTF-8


### 통장목록
GET {{baseUrl}}/account/list HTTP/1.1
Content-Type: application/json; charset=UTF-8


### 회사등록여부 확인
GET {{baseUrl}}/corp/check?checkCorpNum=6348702350 HTTP/1.1
Content-Type: application/json; charset=UTF-8


### 회사등록
POST {{baseUrl}}/corp/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "corpNum": "1073270598",
    "corpName": "아이셋",
    "ceoName": "김희준",
    "bizType": "서비스",
    "bizClass": "프로그래밍",
    "addr1": "서울특별시 마포구 성산동",
    "addr2": "214-18",
    "memberName": "iset",
    "id": "iset12",
    "pwd": "hj@284804",
    "tel": "01020070227",
    "email":"joon0227@gmail.com"
}