@baseUrl = https://localhost:8089
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ0ZmNmZmZkNjdmZWYyMGE1MGZmYWQiLCJpYXQiOjE2OTE2ODAxNTQsImV4cCI6MTY5MTg1Mjk1NH0.ClJW2wcMfPqXIzBatPkGz4Bl4EU-dto_vn25N0QyB9I

### 로그인
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

# {
#     "userId": "bethelean", 
#     "password": "12345678"
# }

{
    "userId": "iset12", 
    "password": "12345678"
}

### 회원가입
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json; charset=UTF-8

# {
#     "userId": "bethelean", 
#     "password": "12345678",
#     "name": "김희준",
#     "email": "bethelean.com@gmail.com",
#     "corpNum": "6348702350",
#     "corpName": "비더린",
#     "url": "bethelean.co.kr",
#     "ceoName": "이혜영",
#     "addr1": "마포구 성산동"
# }

{
    "userId": "iset12", 
    "password": "12345678",
    "name": "김희준",
    "email": "iset@iiiset.com",
    "corpNum": "1073270598",
    "corpName": "비더린",
    "url": "iiiset.com",
    "ceoName": "김희준",
    "addr1": "마포구 성산동"
}

### 사용자 불러오기
GET {{baseUrl}}/user/list HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

### 카드목록
GET {{baseUrl}}/card/list? =1073270598 HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}


### 카드등록
POST {{baseUrl}}/card/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "cardCompany": "HANA",
    "cardType": "C",
    "cardNum": "4336920003113475", 
    "webId": "BETHELEAN",
    "webPwd": "hj@28480404"
}

### 카드삭제
POST {{baseUrl}}/card/stop HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
	"cardNum": "4336920003113475"
}

### 카드내역불러오기
POST {{baseUrl}}/card/log HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "corpNum": "1073270598", 
    "id": "",
    "cardNum": "",
    "baseDate": ""
}


### 통장내역불러오기
POST {{baseUrl}}/account/log HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "id": "BETHELEAN",
    "bankAccountNum": "37691003114104",
    "baseMonth": "202307"
}

### 통장목록
GET {{baseUrl}}/account/list HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
    "id": "BETHELEAN",
    "bankAccountNum": "37691003114104",
    "baseMonth": "202307"
}


### 통장등록
POST {{baseUrl}}/account/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "corpNum": "6348702350",
    "bankAccountType": "C",
    "bank": "HANA",
    "bankAccountNum": "37691003114104",
    "bankAccountPwd": "2848"
}


### 통장목록
GET {{baseUrl}}/account/list HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}


### 통장삭제
DELETE  {{baseUrl}}/account/delete HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{jwt}}

{
    "bankAccountNum": "37691003114104"
}



### 회사등록여부 확인
GET {{baseUrl}}/corp/check?checkCorpNum=6348702350 HTTP/1.1
Content-Type: application/json; charset=UTF-8


### 회사등록
POST {{baseUrl}}/corp/reg HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "corpNum": "1073270598",
    "corpName": "아이셋",
    "ceoName": "김희준",
    "bizType": "서비스",
    "bizClass": "프로그래밍",
    "addr1": "서울특별시 마포구 성산동",
    "addr2": "214-18",
    "memberName": "iset",
    "id": "iset12",
    "pwd": "hj@284804",
    "tel": "01020070227",
    "email":"joon0227@gmail.com"
}