

// export const DefaultCategory = [
//  {order:  10, code: "110", name: "식비", perName: "식비", corpName: "식비", isFixed: false, default: true, },
//  {order:  20, code: "120", name: "카페/간식", perName: "카페/간식", corpName: "카페/간식", isFixed: false, default: true, },
//  {order:  30, code: "130", name: "편의점/마트/잡화", perName: "편의점/마트/잡화", corpName: "편의점/마트/잡화", isFixed: false, default: true, },
//  {order:  40, code: "140", name: "술/유흥", perName: "술/유흥", corpName: "술/유흥", isFixed: false, default: true, },
//  {order:  50, code: "150", name: "쇼핑", perName: "쇼핑", corpName: "쇼핑", isFixed: false, default: true, },
//  {order:  60, code: "160", name: "취미/여가", perName: "취미/여가", corpName: "취미/여가", isFixed: false, default: true, },
//  {order:  70, code: "170", name: "의료/건강/피트니스", perName: "의료/건강/피트니스", corpName: "의료/건강/피트니스", isFixed: false, default: true, },
//  {order:  80, code: "180", name: "주거비", perName: "주거비", corpName: "사무실/임차료", isFixed: false, default: true, },
//  {order:  90, code: "190", name: "통신/전기료", perName: "통신/전기료", corpName: "통신/전기료", isFixed: false, default: true, },
//  {order: 100, code: "200", name: "미용", perName: "미용", corpName: "미용", isFixed: false, default: true, },
//  {order: 110, code: "210", name: "교통/자동차", perName: "교통/자동차", corpName: "교통/자동차", isFixed: false, default: true, },
//  {order: 120, code: "220", name: "여행/숙박", perName: "여행/숙박", corpName: "여행/숙박", isFixed: false, default: true, },
//  {order: 130, code: "230", name: "생활", perName: "생활", corpName: "생활", isFixed: false, default: true, },
//  {order: 140, code: "240", name: "교육", perName: "교육", corpName: "교육", isFixed: false, default: true, },
//  {order: 150, code: "250", name: "저축/투자", perName: "저축/투자", corpName: "저축/투자", isFixed: false, default: true, },
//  {order: 160, code: "260", name: "카드대금", perName: "카드대금", corpName: "카드대금", isFixed: false, default: true, },
//  {order: 170, code: "270", name: "세금", perName: "세금", corpName: "세금", isFixed: false, default: true, },
//  {order: 180, code: "280", name: "보험", perName: "보험", corpName: "보험", isFixed: false, default: true, },
//  {order: 190, code: "290", name: "ATM출금", perName: "ATM출금", corpName: "ATM출금", isFixed: false, default: true, },
//  {order: 200, code: "300", name: "이체", perName: "이체", corpName: "이체", isFixed: false, default: true, },
//  {order: 215, code: "310", name: "기타금융", perName: "기타금융", corpName: "기타금융", isFixed: false, default: true, },
//  {order: 220, code: "320", name: "후불결제대금", perName: "후불결제대금", corpName: "후불결제대금", isFixed: false, default: true, },
//  {order: 230, code: "330", name: "기부/후원", perName: "기부/후원", isFixed: false, default: true, },
//  {order: 240, code: "340", name: "급여", perName: "급여", corpName: "인건비", isFixed: false, default: true, },
//  {order: 250, code: "350", name: "매출", perName: "매출", corpName: "매출", isFixed: false, default: true, },
//  {order: 260, code: "360", name: "복리후생비", perName: "복리후생비", corpName: "복리후생비", isFixed: false, default: true, },
//  {order: 270, code: "370", name: "사대보험", perName: "사대보험", corpName: "사대보험", isFixed: false, default: true, },
//  {order: 280, code: "380", name: "판매/매출", perName: "판매/매출", corpName: "판매/매출", isFixed: false, default: true, },
//  {order: 290, code: "390", name: "퇴직급여", perName: "퇴직급여", isFixed: false, default: true, },
//  {order: 300, code: "400", name: "상품구매", perName: "상품구매", corpName: "상품구매", isFixed: false, default: true, },
//  {order: 310, code: "410", name: "원재료구매", perName: "원재료구매", corpName: "원재료구매", isFixed: false, default: true, },
//  {order: 320, code: "900", name: "미분류", perName: "미분류", corpName: "미분류", isFixed: false, default: true, },
// ];

export const DefaultPersonalCategory = [
  { order:  10, code: "110", name: "식비", },
  { order:  20, code: "120", name: "카페/간식", },
  { order:  30, code: "130", name: "편의점/마트/잡화", },
  { order:  40, code: "140", name: "술/유흥", },
  { order:  50, code: "150", name: "쇼핑", },
  { order:  60, code: "160", name: "취미/여가", },
  { order:  70, code: "170", name: "의료/건강/피트니스", },
  { order:  80, code: "180", name: "주거비", },
  { order:  90, code: "190", name: "통신/전기료", },
  { order: 100, code: "200", name: "미용", },
  { order: 110, code: "210", name: "교통/자동차", },
  { order: 120, code: "220", name: "여행/숙박", },
  { order: 130, code: "230", name: "생활", },
  { order: 140, code: "240", name: "교육", },
  { order: 150, code: "250", name: "예금", },
  { order: 160, code: "260", name: "카드대금", },
  { order: 170, code: "270", name: "세금", },
  { order: 180, code: "280", name: "보험", },
  { order: 190, code: "290", name: "ATM출금", },
  { order: 200, code: "300", name: "이체", },
  { order: 210, code: "310", name: "투자", },
  { order: 220, code: "320", name: "기타금융", },
  { order: 230, code: "330", name: "후불결제대금", },
  { order: 240, code: "340", name: "차입금", },
  { order: 250, code: "350", name: "기부/후원", },
  { order: 260, code: "360", name: "급여", },
  { order: 270, code: "370", name: "잡비", },
  { order: 300, code: "900", name: "미분류", },
];

export const DefaultCorpCategory = [
  { order: 100, code: "400", name: "매출액" },
  { order: 110, code: "410", name: "이자수익" },
  { order: 120, code: "420", name: "매출액" },
  { order: 140, code: "440", name: "배당금수익" },
  { order: 150, code: "450", name: "외환차익" },
  { order: 160, code: "460", name: "투자자산" },
  { order: 170, code: "470", name: "유형자산" },
  { order: 180, code: "480", name: "단기대여금/차입금" },
  { order: 190, code: "490", name: "회사채" },
  { order: 200, code: "500", name: "장기차입금" },
  { order: 210, code: "510", name: "보통예금" },
  { order: 220, code: "520", name: "정기적금" },
  { order: 230, code: "530", name: "정기예금" },
  { order: 240, code: "540", name: "단기투자자산" },
  { order: 250, code: "550", name: "매출채권" },
  { order: 260, code: "560", name: "기타당좌자산" },
  { order: 270, code: "570", name: "투자증권" },
  { order: 280, code: "580", name: "토지" },
  { order: 290, code: "590", name: "설비자산" },
  { order: 300, code: "600", name: "건물" },
  { order: 310, code: "610", name: "기계장치" },
  { order: 320, code: "620", name: "차량운반구" },
  { order: 330, code: "630", name: "급여" },
  { order: 340, code: "640", name: "퇴직급여" },
  { order: 350, code: "650", name: "복리후생비" },
  { order: 360, code: "660", name: "세금과공과" },
  { order: 370, code: "670", name: "임차료" },
  { order: 380, code: "680", name: "접대비" },
  { order: 390, code: "690", name: "광고선전비" },
  { order: 400, code: "700", name: "도서인쇄비" },
  { order: 410, code: "710", name: "비품" },
  { order: 420, code: "720", name: "소모품" },
  { order: 430, code: "730", name: "여비교통비" },
  { order: 440, code: "740", name: "잡비" },
  { order: 450, code: "750", name: "지급수수료" },
  { order: 460, code: "760", name: "차량유지비" },
  { order: 470, code: "770", name: "통신비" },
  { order: 480, code: "780", name: "보험료" },
  { order: 490, code: "790", name: "기타" },
  { order: 500, code: "800", name: "이자비용" },
  { order: 510, code: "810", name: "외환차손" },
  { order: 520, code: "820", name: "외환환산손실" },
  { order: 900, code: "900", name: "미분류" },
];

export const CardCorpCode = [
  {name: "기업BC", code: "3K", baro: ""},
  {name: "광주은행", code: "46", baro: ""},
  {name: "롯데카드", code: "71", baro: "LOTTE"},
  {name: "KDB산업은행", code: "30", baro: ""},
  {name: "BC카드", code: "31", baro: "BC"},
  {name: "삼성카드", code: "51", baro: "SAMSUNG"},
  {name: "새마을금고", code: "38", baro: ""},
  {name: "신한카드", code: "41", baro: "SHINHAN"},
  {name: "신협", code: "62", baro: ""},
  {name: "씨티카드", code: "36", baro: "CITI"},
  {name: "우리BC카드", code: "33", baro: ""},
  {name: "우리카드", code: "W1", baro: "WOORI"},
  {name: "우체국예금보험", code: "37", baro: ""},
  {name: "저축은행중앙회", code: "39", baro: ""},
  {name: "전북은행", code: "35", baro: ""},
  {name: "제주은행", code: "42", baro: ""},
  {name: "카카오뱅크", code: "15", baro: ""},
  {name: "케이뱅크", code: "3A", baro: ""},
  {name: "토스뱅크", code: "24", baro: ""},
  {name: "하나카드", code: "21", baro: "HANA"},
  {name: "현대카드", code: "61", baro: "HYUNDAI"},
  {name: "KB국민카드", code: "11", baro: "KB"},
  {name: "NH농협카드", code: "91", baro: "NH"},
  {name: "Sh수협은행", code: "34", baro: ""},
  {name: "다이너스 클럽	", code: "6D", baro: ""},
  {name: "마스터카드", code: "4M", baro: ""},
  {name: "유니온페이", code: "3C", baro: ""},
  {name: "아메리칸 익스프레스	", code: "7A", baro: ""},
  {name: "JCB", code: "4J", baro: ""},
  {name: "VISA", code: "4V", baro: ""},
];

export const BankCorpCode = [
  {name: "경남은행", code: "039", baro: "KNBANK"},
  {name: "광주은행", code: "034", baro: "KJBANK"},
  {name: "단위농협", code: "012", baro: ""},
  {name: "부산은행", code: "032", baro: "BUSANBANK"},
  {name: "새마을금고", code: "045", baro: "KFCC"},
  {name: "산림조합", code: "064", baro: ""},
  {name: "신한은행", code: "088", baro: "SHINHAN"},
  {name: "신협", code: "048", baro: "CU"},
  {name: "씨티은행", code: "027", baro: "CITI"},
  {name: "우리은행", code: "020", baro: "WOORI"},
  {name: "우체국예금보험", code: "071", baro: "EPOST"},
  {name: "저축은행중앙회", code: "050", baro: ""},
  {name: "전북은행", code: "037", baro: "JBBANK"},
  {name: "제주은행", code: "035", baro: "EJEJUBANK"},
  {name: "카카오뱅크", code: "090", baro: ""},
  {name: "케이뱅크", code: "089", baro: "KBANK"},
  {name: "토스뱅크", code: "092", baro: ""},
  {name: "하나은행", code: "081", baro: "HANA"},
  {name: "홍콩상하이은행", code: "054", baro: ""},
  {name: "IBK기업은행", code: "003", baro: "IBK"},
  {name: "KB국민은행", code: "004", baro: "KB"},
  {name: "DGB대구은행", code: "031", baro: "DGB"},
  {name: "KDB산업은행", code: "002", baro: ""},
  {name: "NH농협은행", code: "011", baro: "NH"},
  {name: "SC제일은행", code: "023", baro: "SC"},
  {name: "Sh수협은행", code: "007", baro: "SUHYUP"},
];

export const SecurityCorpCode = [
  {name: "교보증권", code: "261"},
  {name: "대신증권", code: "267"},
  {name: "메리츠증권", code: "287"},
  {name: "미래에셋증권", code: "238"},
  {name: "부국증권", code: "290"},
  {name: "삼성증권", code: "240"},
  {name: "신영증권", code: "291"},
  {name: "신한금융투자", code: "278"},
  {name: "유안타증권", code: "209"},
  {name: "유진투자증권", code: "280"},
  {name: "카카오페이증권", code: "288"},
  {name: "키움증권", code: "264"},
  {name: "토스증권", code: "271"},
  {name: "펀드온라인코리아", code: "294"},
  {name: "하나금융투자", code: "270"},
  {name: "하이투자증권", code: "262"},
  {name: "한국투자증권", code: "243"},
  {name: "한화투자증권", code: "269"},
  {name: "현대차증권", code: "263"},
  {name: "DB금융투자", code: "279"},
  {name: "KB증권", code: "218"},
  {name: "KTB투자증권", code: "227"},
  {name: "LIG투자증권", code: "292"},
  {name: "NH투자증권", code: "247"},
  {name: "SK증권", code: "266"},
];

export const FinItemCode = [
  {name: "자유입출금식 예금", code: "CHKACC"},
  {name: "정기예금", code: "TIMDEP"},
  {name: "정기적금", code: "INSTSAVACC"},
  {name: "신용카드", code: "CRDCARD"},
  {name: "체크카드", code: "DEBICARD"},
]