export const category = {
  110: { name: "식비", isFixed: false, default: true },
  120: { name: "카페/간식", isFixed: false, default: true },
  130: { name: "편의점/마트/잡화", isFixed: false, default: true },
  140: { name: "술/유흥", isFixed: false, default: true },
  150: { name: "쇼핑", isFixed: false, default: true },
  160: { name: "취미/여가", isFixed: false, default: true },
  170: { name: "의료/건강/피트니스", isFixed: false, default: true },
  180: { name: "주거/통신", isFixed: false, default: true },
  190: { name: "미용", isFixed: false, default: true },
  200: { name: "교통/자동차", isFixed: false, default: true },
  210: { name: "여행/숙박", isFixed: false, default: true },
  220: { name: "생활", isFixed: false, default: true },
  230: { name: "교육", isFixed: false, default: true },

  310: { name: "ATM출금", isFixed: false, default: true },
  320: { name: "보험/세금/기타금융", isFixed: false, default: true },
  330: { name: "후불결제대금", isFixed: false, default: true },
  340: { name: "기부/후원", isFixed: false, default: true },
  350: { name: "저축/투자", isFixed: false, default: true },
  360: { name: "이체", isFixed: false, default: true },
  370: { name: "카드대금", isFixed: false, default: true },
  380: { name: "세금", isFixed: false, default: true },

  510: { name: "급여", isFixed: false, default: true },
  520: { name: "매출", isFixed: false, default: true },
  530: { name: "복리후생비", isFixed: false, default: true },
  540: { name: "사대보험", isFixed: false, default: true },
  550: { name: "잡비", isFixed: false, default: true },

  900: { name: "카테고리 없음", default: true },
};

export const defaultCategory = [
  {
    order: 10,
    kind: "PER",
    code: "110",
    name: "식비",
    isFixed: false,
    default: true,
  },
  {
    order: 20,
    kind: "PER",
    code: "120",
    name: "카페/간식",
    isFixed: false,
    default: true,
  },
  {
    order: 30,
    kind: "PER",
    code: "130",
    name: "편의점/마트/잡화",
    isFixed: false,
    default: true,
  },
  {
    order: 40,
    kind: "PER",
    code: "140",
    name: "술/유흥",
    isFixed: false,
    default: true,
  },
  {
    order: 50,
    kind: "PER",
    code: "150",
    name: "쇼핑",
    isFixed: false,
    default: true,
  },
  {
    order: 60,
    kind: "PER",
    code: "160",
    name: "취미/여가",
    isFixed: false,
    default: true,
  },
  {
    order: 70,
    kind: "PER",
    code: "170",
    name: "의료/건강/피트니스",
    isFixed: false,
    default: true,
  },
  {
    order: 80,
    kind: "PER",
    code: "180",
    name: "주거/통신",
    isFixed: false,
    default: true,
  },
  {
    order: 90,
    kind: "PER",
    code: "190",
    name: "미용",
    isFixed: false,
    default: true,
  },
  {
    order: 100,
    kind: "PER",
    code: "200",
    name: "교통/자동차",
    isFixed: false,
    default: true,
  },
  {
    order: 110,
    kind: "PER",
    code: "210",
    name: "여행/숙박",
    isFixed: false,
    default: true,
  },
  {
    order: 120,
    kind: "PER",
    code: "220",
    name: "생활",
    isFixed: false,
    default: true,
  },
  {
    order: 130,
    kind: "PER",
    code: "230",
    name: "교육",
    isFixed: false,
    default: true,
  },
  {
    order: 140,
    kind: "CMM",
    code: "310",
    name: "ATM출금",
    isFixed: false,
    default: true,
  },
  {
    order: 150,
    kind: "CMM",
    code: "320",
    name: "보험/세금/기타금융",
    isFixed: false,
    default: true,
  },
  {
    order: 160,
    kind: "CMM",
    code: "330",
    name: "후불결제대금",
    isFixed: false,
    default: true,
  },
  {
    order: 170,
    kind: "CMM",
    code: "340",
    name: "기부/후원",
    isFixed: false,
    default: true,
  },
  {
    order: 180,
    kind: "CMM",
    code: "350",
    name: "저축/투자",
    isFixed: false,
    default: true,
  },
  {
    order: 190,
    kind: "CMM",
    code: "360",
    name: "이체",
    isFixed: false,
    default: true,
  },
  {
    order: 200,
    kind: "CMM",
    code: "370",
    name: "카드대금",
    isFixed: false,
    default: true,
  },
  {
    order: 210,
    kind: "BIZ",
    code: "380",
    name: "세금",
    isFixed: false,
    default: true,
  },
  {
    order: 220,
    kind: "BIZ",
    code: "510",
    name: "급여",
    isFixed: false,
    default: true,
  },
  {
    order: 230,
    kind: "BIZ",
    code: "520",
    name: "매출",
    isFixed: false,
    default: true,
  },
  {
    order: 240,
    kind: "BIZ",
    code: "530",
    name: "복리후생비",
    isFixed: false,
    default: true,
  },
  {
    order: 250,
    kind: "BIZ",
    code: "540",
    name: "사대보험",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "550",
    name: "판매비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "560",
    name: "급여",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "570",
    name: "퇴직급여",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "580",
    name: "공과금",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "590",
    name: "임차료",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "600",
    name: "전력비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "610",
    name: "접대비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "620",
    name: "광고선전비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "630",
    name: "보험료",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "640",
    name: "통신비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "650",
    name: "기타판매비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "660",
    name: "관리비",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "670",
    name: "투자처분",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "680",
    name: "유형자산처분",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "690",
    name: "이자비용",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "700",
    name: "세금비용",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "710",
    name: "보통예금",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "720",
    name: "단기투자자산",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "730",
    name: "상품구매",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "740",
    name: "원재료구매",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "750",
    name: "차량운반구",
    isFixed: false,
    default: true,
  },
  {
    order: 300,
    kind: "BIZ",
    code: "760",
    name: "기계장비",
    isFixed: false,
    default: true,
  },
  {
    order: 260,
    kind: "BIZ",
    code: "770",
    name: "잡비",
    isFixed: false,
    default: true,
  },
  {
    order: 270,
    kind: "BIZ",
    code: "990",
    name: "카테고리 없음",
    default: true,
  },
];
